### ISSUE TITLE
Setting layout from command line doesn't work

### ISSUE THREAD

**Issue by baryluk** [ubuntu-mate/mate-tweak#89]
```
$ mate-tweak --get-layout
Window Manager is: marco
System installed layouts: 
['fedora', 'default', 'opensuse']
Current layout: witek-tweak

$ mate-tweak --layout witek-tweak
Window Manager is: marco
System installed layouts: 
['fedora', 'default', 'opensuse']
Current layout: witek-tweak
Switching to: witek-tweak
Found section Customsetting windowcontrollayout
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 1737, in <module>
    mt.replace_panel_layout(args.layout, True)
  File "/usr/bin/mate-tweak", line 768, in replace_panel_layout
    self.enable_applets()
  File "/usr/bin/mate-tweak", line 571, in enable_applets
    pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL, stderr=DEVNULL).pid
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mate-volume-control-applet'
$ 
```

I am on Debian testing, with pretty standard layout, with just added few launchers, cpu frequency and system monitor applets.

mate-tweak 22.04.8-1

**Comment by baryluk** [comment]
Actually it might be because of `mate-media` package was removed from Debian. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971783

Still, it would be good to fall more gracefully.

**Comment by cwendling** [comment]
> Actually it might be because of `mate-media` package was removed from Debian. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971783

The bug mentioned doesn't speak about removal (yet), and it's hasn't.  However, MATE changed the name of the "applet" (that is not really one, it's a status icon) to `mate-volume-control-status-icon`, so you'll have to adjust in your custom profile.

This said indeed maybe mate-tweak could either help the transition, or fail a little more gracefully (maybe simply explaining what's wrong instead of a plain backtrace).

**Comment by 2387skju** [comment]
This is a duplicate of #94
