### ISSUE TITLE
can't change MATE panel layout by mate-tweak because of missed mate-volume-control-applet executable

### ISSUE THREAD

**Issue by N0rbert** [ubuntu-mate/mate-tweak#94]
Steps to reproduce the issue:
1. Install task-mate-desktop with mate-tweak to get full MATE desktop
2. Launch mate-tweak from terminal
3. Go to Panel tab, then try to switch panel layouts using drop-down menu

Expected results:
* user is able to select any available MATE Panel layouts - one from Fedora,
GNOME, openSUSE

Actual results:
* user is unable to select needed panel layout, gets the following error
messages in the terminal:

```
$ mate-tweak
Window Manager is: marco-no-composite
System installed layouts:
['fedora', 'default', 'opensuse']
Current layout: opensuse
/usr/bin/mate-tweak:684: PyGTKDeprecationWarning: The "buttons" argument must
be a Gtk.ButtonsType enum value. Please use the "add_buttons" method for adding
buttons. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL |
Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:684: PyGTKDeprecationWarning: The "flags" argument for
dialog construction is deprecated. Please use initializer keywords: modal=True
and/or destroy_with_parent=True. See:
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL |
Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:690: PyGTKDeprecationWarning: Using positional arguments
with the GObject constructor has been deprecated. Please specify keyword(s) for
"label" or use a class specific constructor. See:
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(text)
Switching to: fedora
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 1047, in combo_fallback
    self.additional_tweaks(schema, key, value[1])
  File "/usr/bin/mate-tweak", line 1031, in additional_tweaks
    self.replace_panel_layout(panel_layout)
  File "/usr/bin/mate-tweak", line 768, in replace_panel_layout
    self.enable_applets()
  File "/usr/bin/mate-tweak", line 571, in enable_applets
    pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL,
stderr=DEVNULL).pid
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mate-volume-control-
applet'
/usr/bin/mate-tweak:684: PyGTKDeprecationWarning: The "buttons" argument must
be a Gtk.ButtonsType enum value. Please use the "add_buttons" method for adding
buttons. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL |
Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:684: PyGTKDeprecationWarning: The "flags" argument for
dialog construction is deprecated. Please use initializer keywords: modal=True
and/or destroy_with_parent=True. See:
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL |
Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:690: PyGTKDeprecationWarning: Using positional arguments
with the GObject constructor has been deprecated. Please specify keyword(s) for
"label" or use a class specific constructor. See:
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(text)
Switching to: default
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 1047, in combo_fallback
    self.additional_tweaks(schema, key, value[1])
  File "/usr/bin/mate-tweak", line 1031, in additional_tweaks
    self.replace_panel_layout(panel_layout)
  File "/usr/bin/mate-tweak", line 768, in replace_panel_layout
    self.enable_applets()
  File "/usr/bin/mate-tweak", line 571, in enable_applets
    pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL,
stderr=DEVNULL).pid
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mate-volume-control-
applet'
/usr/bin/mate-tweak:684: PyGTKDeprecationWarning: The "buttons" argument must
be a Gtk.ButtonsType enum value. Please use the "add_buttons" method for adding
buttons. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL |
Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:684: PyGTKDeprecationWarning: The "flags" argument for
dialog construction is deprecated. Please use initializer keywords: modal=True
and/or destroy_with_parent=True. See:
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL |
Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:690: PyGTKDeprecationWarning: Using positional arguments
with the GObject constructor has been deprecated. Please specify keyword(s) for
"label" or use a class specific constructor. See:
https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(text)
Switching to: opensuse
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 1047, in combo_fallback
    self.additional_tweaks(schema, key, value[1])
  File "/usr/bin/mate-tweak", line 1031, in additional_tweaks
    self.replace_panel_layout(panel_layout)
  File "/usr/bin/mate-tweak", line 768, in replace_panel_layout
    self.enable_applets()
  File "/usr/bin/mate-tweak", line 571, in enable_applets
    pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL,
stderr=DEVNULL).pid
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mate-volume-control-
applet'
```

Please note that Ayatana indicators are not installed.
The same happens on Debian 11 (oldstable, bullseye).

Downstream bug-report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1043291

**Comment by N0rbert** [comment]
Technical details about the bug (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1043291#15 ):

> The problem here is caused by `mate-volume-control-applet` file location.
> It came from `mate-media`, you are right about this package
> Problem persists even with the installed `mate-media` package.
> In Debian 10 (buster) it was located in PATH -
> `/usr/bin/mate-volume-control-applet` (see https://packages.debian.org/search?suite=buster&arch=any&mode=path&searchon=contents&keywords=mate-volume-control-applet ).
> But in Debian 11 and newer it is located in non-PATH place -
`/usr/libexec/mate-volume-control-applet` (see https://packages.debian.org/search?suite=bullseye&arch=any&mode=path&searchon=contents&keywords=mate-volume-control-applet ).
> So it can't be found by `mate-tweak` (see https://sources.debian.org/src/mate-tweak/22.10.0-2/mate-tweak/?hl=78#L571 ).
>
> My local quick and dirty hack is the following:
> ```
> sudo ln -sf /usr/libexec/mate-volume-control-applet /usr/local/bin/mate-volume-control-applet
> ```
> 
> But I would suggest fixing this problem in the `mate-tweak` script - for example you can call this applet by full path -
> `/usr/libexec/mate-volume-control-applet`. 
> It is still applicable for default Debian installation without Ayatana indicators.

**Comment by N0rbert** [comment]
Actually the bug also exists in OpenSuSe Tumbleweed (tested today using openSUSE-Tumbleweed-NET-x86_64-Snapshot20230823-Media.iso). 
Ugly hack for it is the following:

```
sudo ln -sf /usr/libexec/mate-media/mate-volume-control-applet /usr/local/bin/mate-volume-control-applet
```

OS details:

```
$ rpm -qa | grep -E "mate-(media|tweak)" | grep -v lang
mate-media-1.26.1-1.3.x86_64
mate-tweak-22.10.0-1.2.noarch
```

Other RPM-based distros are probably affected too.

**Comment by N0rbert** [comment]
Mageia 9 is affected too.
Ugly fix:
```
sudo ln -sf /usr/libexec/mate-volume-control-applet /usr/local/bin/mate-volume-control-applet
```
Info:
```
$ rpm -qa | grep -E "mate-(media|tweak)"
mate-media-1.26.1-1.mga9
mate-tweak-21.04.3-5.mga9
```

**Comment by N0rbert** [comment]
On Debian 12 (bookworm) this bug may be fixed by using specially created meta-package named [Debian MATE Ayatana Settings](https://github.com/N0rbert/debian-mate-ayatana-settings/) - see its [README.md](https://github.com/N0rbert/debian-mate-ayatana-settings/blob/master/README.md) for installation instuctions. 
This `debian-mate-ayatana-settings` package contains configuration and default settings for Debian with MATE and Ayatana Indicators.

**Comment by cwendling** [comment]
It indeed should look in the libexec directory, see https://github.com/mate-desktop/mate-media/blob/master/mate-volume-control/Makefile.am#L116
However, note that this is only true if built out-of-process, if building in-process what is relevant is the presence of [the applet's library](https://github.com/mate-desktop/mate-media/blob/master/mate-volume-control/Makefile.am#L33).

**Comment by bernarddavis** [comment]
Here is a similar fix for Arch
`
sudo ln -s /usr/lib/mate-media/mate-volume-control-applet /usr/bin/mate-volume-control-applet`

**Comment by 2387skju** [comment]
Not relevant anymore.
<details>

<summary>List of different paths, of the missing file </summary>


A list of the positions of the missing file:

<details>

<summary>File-Position in different Distributions (part of package mate-media) (click)</summary>

| Distribution  | position in /usr/libexec/mate-volume-control-applet | different path
| ------------- | ------------- | ------------- |
| Alpine Linux | yes | 
| AOSC | yes | addational link from /usr/bin/mate-volume-control-applet [ref: aosc.io](https://packages.aosc.io/files/amd64/stable/mate-media/1.28.1)
| Arch Linux | differs | /usr/lib/mate-media/mate-volume-control-applet
| Debian | yes |
| Fedora | differs | /usr/lib64/libmate-volume-control-applet.so [ref: pkgs.org](https://fedora.pkgs.org/rawhide/fedora-x86_64/mate-media-1.28.1-6.fc43.x86_64.rpm.html)
| Gentoo | yes |
| GNU Guix and GNU GuixSD | ?
| Linux Mint | yes |
| Mageia | yes |
| Manjaro | ?
| openSUSE 15.6 | differs | /usr/lib/mate-media/mate-volume-control-applet [ref: pkgs.org](https://opensuse.pkgs.org/15.6/opensuse-oss/mate-media-1.26.1-bp156.1.6.x86_64.rpm.html)
| openSUSE Tumbleweed | differs | /usr/lib64/liblibmate-volume-control-applet.so [ref: pkgs.org](https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/mate-media-1.28.1-2.4.x86_64.rpm.html)
| Parrot Security OS | yes |
| PCLinuxOS | ?
| PLD Linux | ?
| Salix | ?
| Slint | yes |
| Solus | differs | /usr/lib64/mate-media/mate-volume-control-applet [ref: pkgs.org](https://solus.pkgs.org/rolling/solus-shannon-x86_64/mate-media-1.28.1-28-1-x86_64.eopkg.html)
| Trisquel GNU/Linux | yes |
| Ubuntu | yes |
| Ubuntu MATE | yes |
| Uruk GNU/Linux | ?
| Void Linux | differs | /usr/lib/liblibmate-volume-control-applet.so [ref: pkgs.org](https://voidlinux.pkgs.org/current/voidlinux-main-aarch64/mate-media-1.28.1_1.aarch64.xbps.html)
|  | 
| Slackware (third party) | yes |
| OpenMandriva | yes |
| RHEL 9 | yes |
| Alt Linux | differs | /usr/lib64/libmate-volume-control-applet.so
|  | 
| FreeBSD | differs | /usr/local/libexec/mate-volume-control-applet [ref: pkgs.org](https://freebsd.pkgs.org/14/freebsd-amd64/mate-media-1.28.1_1.pkg.html)
| openIndian | differs | usr/libexec/mate/mate-volume-control-applet [ref: openindiana.org](https://pkg.openindiana.org/hipster/manifest/0/desktop%2Fmate%2Fmate-media@1.28.1%2C5.11-2025.0.0.1%3A20250322T073445Z)
| NetBsd | differs | /libexec/mate-volume-control-applet [ref: pkgs.org](https://netbsd.pkgs.org/10/netbsd-amd64/mate-media-1.26.2nb11.tgz.html)
</details>

<details>

<summary>Consolidated: found paths (click)</summary>
   /usr/libexec/mate-volume-control-applet

   /usr/lib/mate-media/mate-volume-control-applet

   /usr/lib64/mate-media/mate-volume-control-applet

   /usr/local/libexec/mate-volume-control-applet

   /usr/libexec/mate/mate-volume-control-applet

   /lib/mate-media/mate-volume-control-applet     ??

   /libexec/mate-volume-control-applet
</details>

.so files: Some Distributions already removed mate-volume-control-applet
They already removed the mate-volume-control-applet. They leave just a .so file. This .so file can't started directly or via .desktop file. (At least the one I tested in OpenSuse Tumbleweed). <details>
<summary>.so file  positions (click)</summary>

   /usr/lib64/libmate-volume-control-applet.so
   /usr/lib64/liblibmate-volume-control-applet.so
   /usr/lib/liblibmate-volume-control-applet.so
</details>
</details>

**Comment by 2387skju** [comment]
The Volume Control has changed in MATE:
> ...MATE changed the name of the "applet" (that is not really one, it's a status icon) to mate-volume-control-status-icon... Quote by "cwendling" [here on github/mate-tweak ](https://github.com/ubuntu-mate/mate-tweak/issues/89#issuecomment-1237786574)

mate-volume-control-**applet** is the 'old' way. (It still existing, but not in all distributions)
mate-volume-control-**status-icon** is the new one. It shows in the notification area.

Both could run at the same time:
<img width="322" height="427" alt="Screenshot of both Volume Controls, running at the same time" src="https://github.com/user-attachments/assets/0a560f42-e986-4499-a049-66a6e757f33e" />

-----

The way to start the volume control has also changed:
Old: `user@computer:~$ mate-volume-control-applet` is NOT working and NOT needed anymore. The Applet start itself.
New: `user@computer:~$ mate-volume-control-status-icon`


-----
**If the applet was complete removed by a Distribution (currently rare):** 
The applet is still part in some Layouts (e.g.: Fedora.layout) ((The Layout files came directly from Mate-Panel package)).
The distribution OpenSuse Tumbleweed  decided to remove the Volume applet completely. (At least i can't found, or add this applet anymore). ((seems that OpenSuse forget to remove the applet also from the Fedora.layout.))
These Users will see this Error:
<img width="413" height="126" alt="Screenshot:  Content similar to: This results in a Error Message (at least once): can't start Applet GvcAppletFactory::GvcApplet - Buttons: keep applet - remove applet" src="https://github.com/user-attachments/assets/dcf20729-b6a8-41eb-9476-b8224459218e" />

**Comment by 2387skju** [comment]
I've submitted a fix Pull-Request: #111

---
---
---


For the impatient users: I suggest this workaround:
## A simple workaround:

### 1. If you have <ins>no</ins> root-right / sudo:

Start Mate-Tweak that way ([ref](https://github.com/linuxmint/mint21.2-beta/issues/71)):
Insert in terminal: `PATH=$PATH:/usr/libexec mate-tweak`
Supported Distributions:
- This should work on: debian/Ubuntu/gentoo/Mageia/OpenMandriva/RHEL
- You may have to change the path ([see table in comment above](https://github.com/ubuntu-mate/mate-tweak/issues/94#issuecomment-3350823421)) on: Arch , *BSD, Solus
- May not work on (at least i think so): Fedora, openSUSE, Void Linux, Alt Linux

### 2. If you have root-right / sudo:

Just comment out the error line:
 - start text-editor with root right in terminal: `sudo pluma /bin/mate-tweak`
 - go to line 571
 - write a **#** at the beginning of the line:
         Before:
        `  pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL, stderr=DEVNULL).pid`
         After:
         `# pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL, stderr=DEVNULL).pid`

That's all, for non-Ayantana Users (they should do also the next step).
(Alternative Fix: replace all (in the complete file) `mate-volume-control-applet` with `mate-volume-control-status-icon`. This is maybe a bedder quick fix. Also the next step is not needed anymore (=autostart in Ayantana is correct) )


### 3. Users of Ayantana
If you have installed [ayantana](https://ayatanaindicators.github.io/about/), you will currently see two volume controls running at the same time. 
<img width="496" height="54" alt="Image" src="https://github.com/user-attachments/assets/064d3504-4e82-4a59-ab21-de4c1d76b948" />

You can disable it in the Startup Applications-Manager:
 - start the Startup Applications - Manager (e.g. in terminal by `mate-session-properties`)
 - click on: [x] show hidden
 - uncheck Volumn Control (maybe you have two entrys: disable both)
 - It's done: After Re-login you have only one volume control

<img width="502" height="415" alt="Image" src="https://github.com/user-attachments/assets/c46573b2-0210-4d4f-b2bf-3a8cf9db9706" />
